# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ITApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ITApp
  pod 'SnapKit'
  pod 'Kingfisher'

  target 'ITAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ITAppUITests' do
    # Pods for testing
  end

end
