//
//  ___FILEBASENAME___.swift
//  ___PROJECTNAME___
//
//  Created by ___FULLUSERNAME___ on ___DATE___.
//  Copyright (c) ___YEAR___ iOS@Taipei in iPlayground 2020. All rights reserved.
//
//  This file was generated by iOS@Taipei's Clean Architecture Xcode Templates, which
//  is goaled to help you apply clean architecture to your iOS projects,
//

import Foundation

protocol ___VARIABLE_productName___BusinessLogic {
    //    func doSomething(request: ___VARIABLE_productName___.<#T##EventName#>.<#T##Request#>)
}

final class ___VARIABLE_productName___Interactor: ___VARIABLE_productName___BusinessLogic {
    
    private var presenter: ___VARIABLE_productName___PresentationLogic?
    
    //    private let <#T##WorkerName#>Worker: <#T##WorkerType#>
    
    init() {
        //        self.<#T##WorkerName#>worker = .init()
    }
    
    //    func doSomething(request: ___VARIABLE_productName___.<#T##EventName#>.<#T##Request#>) {
    //
    //    }
}

// MARK: - Private funcs
extension ___VARIABLE_productName___Interactor {
    
}

// MARK: - Constants
extension ___VARIABLE_productName___Interactor {
    
}
