//
//  ___FILEBASENAME___.swift
//  ___PROJECTNAME___
//
//  Created by ___FULLUSERNAME___ on ___DATE___.
//  Copyright (c) ___YEAR___ iOS@Taipei in iPlayground 2020. All rights reserved.
//
//  This file was generated by iOS@Taipei's Clean Architecture Xcode Templates, which
//  is goaled to help you apply clean architecture to your iOS projects,
//

import Foundation

enum ___VARIABLE_productName___ {

    // MARK: - Use cases

    enum <#T##EventName#> {
        struct Request {
        }

        struct Response {
        }

        struct ViewModel {
        }
    }
}
