//
//  ___FILEBASENAME___.swift
//  ___PROJECTNAME___
//
//  Created by ___FULLUSERNAME___ on ___DATE___.
//  Copyright (c) ___YEAR___ iOS@Taipei in iPlayground 2020. All rights reserved.
//
//  This file was generated by iOS@Taipei's Clean Architecture Xcode Templates, which
//  is goaled to help you apply clean architecture to your iOS projects,
//

import Foundation

protocol ___VARIABLE_productName___PresentationLogic {
    //    func presentSomething(response: ___VARIABLE_productName___.Something.Response)
}

final class ___VARIABLE_productName___Presenter: ___VARIABLE_productName___PresentationLogic {
    
    private weak var viewController: ___VARIABLE_productName___DisplayLogic?
    
    //    func presentSomething(response: ___VARIABLE_productName___.<#T##EventName#>.<#T##Request#>) {
    //        let viewModel = ___VARIABLE_productName___.<#T##EventName#>.<#T##ViewModelName#>()
    //        viewController?.displaySomething(viewModel: viewModel)
    //    }
}

// MARK: - Private funcs
extension ___VARIABLE_productName___Presenter {
    
}

// MARK: - Constants
extension ___VARIABLE_productName___Presenter {
    
}
